scenario_order/routes.py
from flask import Blueprint, render_template, session, request, redirect, url_for, current_app
from scenario_auth.sql_provider import SQLProvider
from database import make_update, work_with_db
from scenario_order.utils import add_to_basket, clear_basket, clear_client
import datetime


basket_app = Blueprint('basket', __name__, template_folder='templates')
provider = SQLProvider("scenario_order/sql/")


@basket_app.route('/', methods=['GET', 'POST'])
def client_order():
    if request.method == "GET":
        sql = provider.get('client_list.sql')
        clients = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("choose_client.html", clients=clients)
    else:
        client_id = request.form['client_id']
        session['client_id'] = client_id
        if not client_id:
            return 'clients not found'
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/order-menu', methods=['GET', 'POST'])
def list_order_handler():
    sql = provider.get('final_client.sql', id_client=session.get('client_id'))
    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    client_name = result[0]['name']
    genres = ['Romance', 'Fantasy', 'YA(Young Adult)', 'Biography', 'Adventure']
    if request.method == "GET":
        point = request.args.get('point', None)
        current_basket = session.get('basket', [])
        if point:
            sql = provider.get('book_list_romance.sql', rom=point)
        else:
            sql = provider.get('books_list.sql')
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("book_order_list.html", books=books, basket=current_basket, genres=genres, client=client_name)
    else:
        book_id = request.form['book_id']
        sql = provider.get('order_book.sql', book_id=book_id)
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        if not books:
            return 'Books not found'
        add_to_basket(books)
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/basket', methods=['GET', 'POST'])
def basket():
    if request.method == 'GET':
        items = work_with_db(current_app.config['DB_CONFIG'], provider.get('list.sql'))
        return render_template('list.html', items=items, heads=['Мебель', "Цена"])
    else:
        item_id = request.form.get("item_id")
        i_id = int(item_id)
        sql = provider.get('delete_item.sql', item_id=i_id)
        response = make_update(current_app.config['DB_CONFIG'], sql)
    return redirect(url_for('basket.basket'))


@basket_app.route('/order-menu-genre', methods=['GET', 'POST'])
def book_genre():
    if request.method == "GET":
        current_basket = session.get('basket', [])
        sql = provider.get('books_list.sql')
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("book_order_list.html", books=books, basket=current_basket)
    else:
        if request.form['genre_book']:
            return redirect(url_for('basket.book_genre'))
        book_id = request.form['book_id']
        sql = provider.get('order_book.sql', book_id=book_id)
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        if not books:
            return 'Books not found'
        add_to_basket(books)
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/insert', methods=['GET', 'POST'])
def insert():
    if request.method == "GET":
        return render_template("insert_item.html")
    else:
        item_name = request.form.get('item_name')
        price = request.form.get('price')
        sql = provider.get('insert.sql', item_name=item_name, price=price)
        response = make_update(current_app.config['DB_CONFIG'], sql)
    return redirect(url_for('basket.basket'))


@basket_app.route('/buy')
def buy_basket_handler():
    current_basket = session.get('basket', [])
    if current_basket:
        now = datetime.datetime.now()
        sql = provider.get('insert_order_client.sql', current_time=now, id_client=session.get('client_id'))
        response = make_update(current_app.config['DB_CONFIG'], sql)
        sql2 = provider.get('take_order_id.sql', id_client=session.get('client_id'))
        id_order = work_with_db(current_app.config['DB_CONFIG'], sql2)
        int_id = id_order[0]['order_id']
        for book in current_basket:
            sql3 = provider.get('insert_basket_order.sql', id_Order=int_id, book_Id=book['idbook'], book_Name=book['Name'], book_Genre=book['Genre'])
            response = make_update(current_app.config['DB_CONFIG'], sql3)
        return redirect(url_for('basket.success'))
    return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/success', methods=['GET', 'POST'])
def success():
    sql = provider.get('final_client.sql', id_client=session.get('client_id'))
    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    client_name = result[0]['name']
    text = "Составлен заказ для читателя "
    clear_client()
    return render_template("success_order.html", text=text, user=client_name)


@basket_app.route('/buy2')
def buy_basket_handler2():
    current_basket = session.get('basket', [])
    if current_basket:
        dict_of_items = {}
        print(current_basket)
        for product in current_basket:
            id = product['item_id']
            if id not in dict_of_items:
                dict_of_items[id] = 1
            elif id in dict_of_items:
                dict_of_items[id] += 1
        for key in dict_of_items:
            sql = provider.get('insert_basket.sql', item_id=key, amount=dict_of_items[key])
            response = make_update(current_app.config['DB_CONFIG'], sql)
        return redirect(url_for('basket.clear_basket_handler'))
    return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/clear')
def clear_basket_handler():
    clear_basket()
    return redirect(url_for('basket.list_order_handler'))

scenario_order/templates/basket_order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

{% import 'basket_utils.html' as utils %}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h2>Список товаров</h2>
            {% if items %}
            {% for item in items %}
            {{ utils.render_item(item, show_form = True) }}
            {% endfor %}
            {% else %}
            <p>Нет доступных товаров</p>
            {% endif %}
        </div>
        <div class="col-md-5">
            <h2>Ваша корзина</h2>
            {% if basket %}
            {% for item in basket %}
            {{ utils.render_item(item, show_form = False)}}
            {% endfor %}
            {% else %}
            <p>Корзина пуста</p>
            {% endif %}
        </div>
        <div class="col-md-2">
            <a href="{{url_for('basket.clear_basket_handler')}}">Очистить корзину</a>
            <a href="{{url_for('basket.buy_basket_handler')}}">Купить</a>
        </div>
    </div>
</div>
</body>
</html>

scenario_order/templates/basket_utils.html
{% macro render_item(item, show_form=False) %}
<div style="border-style: solid; border-color: aqua; margin: 10px">
    <p>
        <span>Название: {{item['name']}}</span>
        <span>Цена: {{item['price']}}</span>
        <span>Описание: {{item['description']}}</span>
    </p>
    {% if show_form %}
    <div>
        <form action="" method="post">
            <input class="button is-primary" type="submit" value="Добавить">
            <input type="hidden" name="item_id" value="{{item['item_id']}}">
        </form>
    </div>

    {% endif %}
</div>
{% endmacro %}

scenario_order/templates/book_order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<body>

{% import 'book_utils.html' as utils %}

<div class="container">
    <div class="columns">
        <div class="column is-2">
            <h2 class="title is-3">Вывести книги по жанрам</h2>
            {% if genres %}
            {% for genre in genres %}
            <form style="width: 33%;">
            <a href="{{url_for('basket.list_order_handler')}}?point={{genre}}" align="center" class="button is-right">{{genre}}</a>
            </form>
            <br>
            {% endfor %}
            {% else %}
            <p>Нет данных</p>
            {% endif %}
            <form style="width: 33%;">
            <a href="{{url_for('basket.list_order_handler')}}" align="center" class="button is-right">Все жанры</a>
            </form>
        </div>
        <div class="column is-4">
            <h2 class="title is-3" align="center">Список книг</h2>
            {% if books %}
            {% for book in books %}
            {{ utils.render_item(book, show_form = True) }}
            {% endfor %}
            {% else %}
            <p>Нет доступных книг</p>
            {% endif %}
        </div>
        <div class="column is-4">
            <h2 class="title is-3" align="center">Заказ</h2>
            {% if basket %}
            {% for book in basket %}
            {{ utils.render_item(book, show_form = False)}}
            {% endfor %}
            {% else %}
            <p>Заказ пуст</p>
            {% endif %}
        </div>
        <div class="column is-2">
            <div class="box" align="center">
                <div class="content">
                <p align="center">Читатель: {{client}}</p>
                </div>
                <a class="button is-primary" href="{{url_for('basket.buy_basket_handler')}}">Заказать</a>
                <br>
                <br>
                <a class="button is-primary" href="{{url_for('basket.clear_basket_handler')}}">Отменить заказ</a>
                <br>
                <br>
                <a class="button is-primary" href="{{url_for('navbar')}}">Главное меню</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

scenario_order/templates/book_utils.html
{% macro render_item(book, show_form=False) %}
<div class="box" style="border-style: solid; border-color: hsl(171, 100%, 41%); margin: 10px">
    <div class="columns">
        <div class="column is-7">
            <p>
                <span>Название: {{book['Name']}}</span>
                <br>
                <span>Автор: {{book['Author']}}</span>
                <br>
                <span>Жанр: {{book['Genre']}}</span>
                <br>
            </p>
        </div>
        {% if show_form %}
        <div class="column is-4">
            <form action="" method="post">
                <br>
                <br>
                <input class="button is-primary" type="submit" value="Добавить">
                <input type="hidden" name="book_id" value="{{book['idbook']}}">
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

scenario_order/templates/choose_client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<body>
{% import 'client_utils.html' as utils %}
<h1 class="title" style="margin-left: 6px">Выбор читателя для составления заказа</h1>
<aside class="menu" style="margin-left: 6px">
  <div class="content">
    <p>Выберите читателя для дальнейшего составления заказа</p>
      <p> Вернуться в <a href="{{url_for('navbar')}}">Главное меню</a></p>
  </div>
</aside>

<div class="columns">
  <div class="column is-6">
      {% if clients %}
      {% for client in clients %}
      {{ utils.render_item(client, show_form = True) }}
      {% endfor %}
      {% else %}
      <p>Нет доступных читателей</p>
      {% endif %}
  </div>
</div>
</body>
</html>

scenario_order/templates/client_utils.html
{% macro render_item(client, show_form=False) %}
<div class="box" style="border-style: solid; border-color: hsl(171, 100%, 41%); margin: 10px">
    <div class="columns">
        <div class="column is-9">
            <p>
            <span>ФИО читателя: {{client['name']}}</span>
            <br>
            <span>Почта: {{client['mail']}}</span>
            </p>
        </div>
        {% if show_form %}
        <div class="column is-2">
            <form action="" method="post">
                <input class="button is-primary" type="submit" value="Выбрать">
                <input type="hidden" name="client_id" value="{{client['client_id']}}">
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

scenario_order/templates/insert_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insert item</title>
</head>
<body>
<div align="center">
    Введите новый товар <br><br>
    <form action="" method="post">
        <input type="text" name="item_name" placeholder="Название товара"><br><br>
        <input type="text" name="price" placeholder="Цена"><br><br>
        <input type="submit" name="insert" value="Добавить"><br><br>
    </form>

</div>

</body>
</html>

scenario_order/templates/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-
        scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    </head>
    <title>Корзина</title>
<body>
<div>
    <h1>Все товары</h1>
    <a href="{{url_for('basket.insert')}}">Добавить товар</a> <br>
    <a href="{{url_for('navbar')}}">Вернуться в главное меню</a>
</div>
{% if items %}
<div align="center">
    <table border="0" width="50%">
        {% for head in heads %}
        <th align="left"> {{head}}</th>
        {% endfor %}
        {% for item in items %}
        <tr>
            <td> {{item['name']}}</td>
                <td> {{item['price']}}</td>
            <td>
                <form action="" method="post">
                    <input type="hidden" name="item_id" value="{{item['item_id']}}">
                    <input type="submit" name="action" value="Удалить">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
</body>
</html>

scenario_order/templates/success_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Error</title>
</head>
<body>
<div class="notification is-primary">
  <button class="delete"></button>
    {{text}} {{user}}
    <br>
    Вернуться в <a style="margin-left: 6px" href="{{url_for('basket.clear_basket_handler')}}">меню составления заказа</a>
</div>
</body>
</html>