app.py
import json

from flask import Flask, render_template, session  # глобальный объект приложения импортируем
from search.search import search
from scenario_auth.routes import auth_app
from scenario_order.routes import basket_app


app = Flask(__name__)  # __name__ имя модуля, точка входа
app.register_blueprint(search, url_prefix='/search')
app.register_blueprint(auth_app, url_prefix='/auth')
app.register_blueprint(basket_app, url_prefix="/new_order")

app.config['SECRET_KEY'] = 'I am the only one'
app.config['ACCESS_CONFIG'] = json.load(open('configs/access.json'))

app.config['DB_CONFIG'] = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'password': 'root',
    'db': 'Library'
}


@app.route("/")  # @ - декоратор, на входящий урл будет срабатывать эта функция, обработчик
def navbar():
    if 'client_id' in session:
        session.pop('client_id')
    if 'basket' in session:
        session.pop('basket')
    return render_template("navbar.html")


@app.route("/exit")
def exit():
    for key in list(session.keys()):
        session.pop(key)
    return render_template("exit.html", text='Вы вышли из системы.')


if __name__ == "__main__":
    app.debug = True
    app.run(host="127.0.0.1", port=5012)

scenario_auth/routes.py
import os

from flask import Blueprint, render_template, session, request, current_app
from scenario_auth.sql_provider import SQLProvider
from database import work_with_db

auth_app = Blueprint('auth', __name__, template_folder='templates')
provider = SQLProvider("scenario_auth/sql/")


@auth_app.route('/', methods=['GET', 'POST'])
def login_page():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        login = request.form.get('login', None)
        password = request.form.get('password', None)
        sql = provider.get('find_group.sql', login=login, password=password)
        if not sql or not login or not password:
            return render_template('not_correct_data.html')
        else:
            user_group = str(work_with_db(current_app.config['DB_CONFIG'], sql))[17:-3]
            if user_group:
                session['group_name'] = user_group
                return render_template('back_in_menu.html', text="Вы авторизованы как ", user=str(user_group))
            else:
                return render_template('login.html', error='Вы не авторизованы в системе. ')

scenario_order/routes.py
from flask import Blueprint, render_template, session, request, redirect, url_for, current_app
from scenario_auth.sql_provider import SQLProvider
from database import make_update, work_with_db
from scenario_order.utils import add_to_basket, clear_basket, clear_client
import datetime


basket_app = Blueprint('basket', __name__, template_folder='templates')
provider = SQLProvider("scenario_order/sql/")


@basket_app.route('/', methods=['GET', 'POST'])
def client_order():
    if request.method == "GET":
        sql = provider.get('client_list.sql')
        clients = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("choose_client.html", clients=clients)
    else:
        client_id = request.form['client_id']
        session['client_id'] = client_id
        if not client_id:
            return 'clients not found'
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/order-menu', methods=['GET', 'POST'])
def list_order_handler():
    sql = provider.get('final_client.sql', id_client=session.get('client_id'))
    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    client_name = result[0]['name']
    genres = ['Romance', 'Fantasy', 'YA(Young Adult)', 'Biography', 'Adventure']
    if request.method == "GET":
        point = request.args.get('point', None)
        current_basket = session.get('basket', [])
        if point:
            sql = provider.get('book_list_romance.sql', rom=point)
        else:
            sql = provider.get('books_list.sql')
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("book_order_list.html", books=books, basket=current_basket, genres=genres, client=client_name)
    else:
        book_id = request.form['book_id']
        sql = provider.get('order_book.sql', book_id=book_id)
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        if not books:
            return 'Books not found'
        add_to_basket(books)
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/basket', methods=['GET', 'POST'])
def basket():
    if request.method == 'GET':
        items = work_with_db(current_app.config['DB_CONFIG'], provider.get('list.sql'))
        return render_template('list.html', items=items, heads=['Мебель', "Цена"])
    else:
        item_id = request.form.get("item_id")
        i_id = int(item_id)
        sql = provider.get('delete_item.sql', item_id=i_id)
        response = make_update(current_app.config['DB_CONFIG'], sql)
    return redirect(url_for('basket.basket'))


@basket_app.route('/order-menu-genre', methods=['GET', 'POST'])
def book_genre():
    if request.method == "GET":
        current_basket = session.get('basket', [])
        sql = provider.get('books_list.sql')
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        return render_template("book_order_list.html", books=books, basket=current_basket)
    else:
        if request.form['genre_book']:
            return redirect(url_for('basket.book_genre'))
        book_id = request.form['book_id']
        sql = provider.get('order_book.sql', book_id=book_id)
        books = work_with_db(current_app.config['DB_CONFIG'], sql)
        if not books:
            return 'Books not found'
        add_to_basket(books)
        return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/insert', methods=['GET', 'POST'])
def insert():
    if request.method == "GET":
        return render_template("insert_item.html")
    else:
        item_name = request.form.get('item_name')
        price = request.form.get('price')
        sql = provider.get('insert.sql', item_name=item_name, price=price)
        response = make_update(current_app.config['DB_CONFIG'], sql)
    return redirect(url_for('basket.basket'))


@basket_app.route('/buy')
def buy_basket_handler():
    current_basket = session.get('basket', [])
    if current_basket:
        now = datetime.datetime.now()
        sql = provider.get('insert_order_client.sql', current_time=now, id_client=session.get('client_id'))
        response = make_update(current_app.config['DB_CONFIG'], sql)
        sql2 = provider.get('take_order_id.sql', id_client=session.get('client_id'))
        id_order = work_with_db(current_app.config['DB_CONFIG'], sql2)
        int_id = id_order[0]['order_id']
        for book in current_basket:
            sql3 = provider.get('insert_basket_order.sql', id_Order=int_id, book_Id=book['idbook'], book_Name=book['Name'], book_Genre=book['Genre'])
            response = make_update(current_app.config['DB_CONFIG'], sql3)
        return redirect(url_for('basket.success'))
    return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/success', methods=['GET', 'POST'])
def success():
    sql = provider.get('final_client.sql', id_client=session.get('client_id'))
    result = work_with_db(current_app.config['DB_CONFIG'], sql)
    client_name = result[0]['name']
    text = "Составлен заказ для читателя "
    clear_client()
    return render_template("success_order.html", text=text, user=client_name)


@basket_app.route('/buy2')
def buy_basket_handler2():
    current_basket = session.get('basket', [])
    if current_basket:
        dict_of_items = {}
        print(current_basket)
        for product in current_basket:
            id = product['item_id']
            if id not in dict_of_items:
                dict_of_items[id] = 1
            elif id in dict_of_items:
                dict_of_items[id] += 1
        for key in dict_of_items:
            sql = provider.get('insert_basket.sql', item_id=key, amount=dict_of_items[key])
            response = make_update(current_app.config['DB_CONFIG'], sql)
        return redirect(url_for('basket.clear_basket_handler'))
    return redirect(url_for('basket.list_order_handler'))


@basket_app.route('/clear')
def clear_basket_handler():
    clear_basket()
    return redirect(url_for('basket.list_order_handler'))

templates/back_in_menu_nv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Error</title>
</head>
<body>
<div class="notification is-danger">
  <button class="delete"></button>
    {{text}} Вернуться в <a href="{{url_for('navbar')}}">Главное меню</a>.
</div>
</body>
</html>

templates/exit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Error</title>
</head>
<body>
<div class="notification is-primary">
  <button class="delete"></button>
    {{text}} Вернуться в <a href="{{url_for('navbar')}}">Главное меню</a>.
</div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<body>
<h1 class="title" style="margin-left: 6px">Библиотека им. Н. А. Некрасова</h1>
<h2 class="subtitle is-4" style="margin-left: 6px">Добро пожаловать!</h2>
<aside class="menu" style="margin-left: 6px">
  <div class="content">
  <p>Для дальнейшей работы вам необходимо авторизоваться. После авторизации вы сможете работать только с теми пунктами меню, которые вам доступны.</p>
  <p>Подробная инструкция по работе с данной информационной системой доступна по
  <a class="has-text-link" href="https://www.google.com">ссылке</a>.</p>
</div>
  <p class="menu-label">
    Главное меню
  </p>
  <ul class="menu-list">
    <li><a href="{{url_for('auth.login_page')}}"> Авторизация </a></li>
    <li><a href="{{url_for('search.main')}}">Работа с оперативной информацией</a></li>
    <li><a href="{{url_for('basket.client_order')}}"> Создание нового заказа </a></li>
    <li><a href="{{url_for('exit')}}">Выход из системы</a></li>
  </ul>
</aside>
</body>
</html>